### ISSUE TITLE
`IndexAny` for automatic `/dev/nbdX` selection is invalid?

### ISSUE THREAD

**Issue by bduffany** [Merovius/nbd#16]
Hi there, I'm experimenting with this package in an attempt to provide nbd-backed storage as part of our remote execution subsystem in https://github.com/buildbuddy-io/buildbuddy

I tried running `nbd lo` with the following steps (running from the commit in https://github.com/Merovius/nbd/pull/15 to fix build issues):

```
sudo modprobe nbd
mkdir -p /tmp/nbd/root
mke2fs -N 0 -O '^64bit' -d /tmp/nbd/root -m 5 -r 1 -t ext4 /tmp/nbd/image.ext4 '100M'
go build -o . ./...
./nbd lo /tmp/nbd/image.ext4
```

but I got this output:

```
2023/05/31 14:56:17 104857600
2023/05/31 14:56:17 netlink receive: invalid argument
```

in the kernel logs, I see

```
[16137.557266] nbd: illegal input index -1
```

From my debugging, I see that -1 is `nbdnl.IndexAny` if converted from uint32 to int32.

If I change `nbdnl.IndexAny` to `0` in `Configure`, it works swimmingly.

Is there a minimum kernel version requirement or some other requirement to support `IndexAny`? I am on kernel version `5.15.0-72-generic`

Also, would you be open to PRs to make the device number configurable? In my case, I know ahead of time that I would like to use nbd0 and nbd1, since I am running this from a fresh VM.

**Comment by Merovius** [comment]
I think there was an extra check for the index added since I last touched this, which exposed my misunderstanding of the semantics.

> Hi there, I'm experimenting with this package in an attempt to provide nbd-backed storage as part of our remote execution subsystem in https://github.com/buildbuddy-io/buildbuddy

Cool. I'm happy if it turns out to be useful. As a general fair warning: You might have noticed that I haven't maintained this project terribly well. The project I intended to use this for never really came to anything. I'll try and respond to issues and continue to maintain this, but I can't promise you'll be happy with the general quality. I wouldn't be mad about a fork, if you prefer to maintain it yourself.

> Also, would you be open to PRs to make the device number configurable?

Can you file a new issue to discuss this? I feel relatively strongly that the current semantics are correct and I don't want to have too much API surface. But I might be convinced. There might also be other things we can do to solve the issue you have with letting the kernel chose - if you could give some detail on how it makes your life harder, that would be appreciated.
